
#Autogenerated schema
from openpyxl.descriptors.serialisable import Serialisable
from openpyxl.descriptors import (
    Typed,)


class AreaChart(Serialisable):

    as_3D = True

    gapDepth = Typed(expected_type=GapAmount, allow_none=True, nested=True)
    axId = Typed(expected_type=UnsignedInt, )
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    __elements__ = ('gapDepth', 'axId', 'extLst')

    def __init__(self,
                 axId=None,
                 extLst=None,
                ):
        self.axId = axId
        self.extLst = extLst

