
#Autogenerated schema
from openpyxl.descriptors.serialisable import Serialisable
from openpyxl.descriptors import (
    Typed,
    Set,)


class Shape(Serialisable):

    val = Set(values=(['cone', 'coneToMax', 'box', 'cylinder', 'pyramid', 'pyramidToMax']))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class BarSer(Serialisable):

    invertIfNegative = Bool(nested=True, allow_none=True)
    pictureOptions = Typed(expected_type=PictureOptions, allow_none=True)
    dPt = Typed(expected_type=DPt, allow_none=True)
    dLbls = Typed(expected_type=DLbls, allow_none=True)
    trendline = Typed(expected_type=Trendline, allow_none=True)
    errBars = Typed(expected_type=ErrBars, allow_none=True)
    cat = Typed(expected_type=AxDataSource, allow_none=True)
    val = Typed(expected_type=NumDataSource, allow_none=True)
    shape = Typed(expected_type=Shape, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    __elements__ = ('invertIfNegative', 'pictureOptions', 'dPt', 'dLbls', 'trendline', 'errBars', 'cat', 'val', 'shape', 'extLst')

    def __init__(self,
                 invertIfNegative=None,
                 pictureOptions=None,
                 dPt=None,
                 dLbls=None,
                 trendline=None,
                 errBars=None,
                 cat=None,
                 val=None,
                 shape=None,
                 extLst=None,
                ):
        self.invertIfNegative = invertIfNegative
        self.pictureOptions = pictureOptions
        self.dPt = dPt
        self.dLbls = dLbls
        self.trendline = trendline
        self.errBars = errBars
        self.cat = cat
        self.val = val
        self.shape = shape
        self.extLst = extLst


class BarGrouping(Serialisable):

    val = Set(values=(['percentStacked', 'clustered', 'standard', 'stacked']))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class BarDir(Serialisable):

    val = Set(values=(['bar', 'col']))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class BarChartShared(Serialisable):

    barDir = Typed(expected_type=BarDir, )
    grouping = Typed(expected_type=BarGrouping, allow_none=True)
    varyColors = Bool(nested=True, allow_none=True)
    ser = Typed(expected_type=BarSer, allow_none=True)
    dLbls = Typed(expected_type=DLbls, allow_none=True)

    __elements__ = ('barDir', 'grouping', 'varyColors', 'ser', 'dLbls')

    def __init__(self,
                 barDir=None,
                 grouping=None,
                 varyColors=None,
                 ser=None,
                 dLbls=None,
                ):
        self.barDir = barDir
        self.grouping = grouping
        self.varyColors = varyColors
        self.ser = ser
        self.dLbls = dLbls

