#Autogenerated schema
from .LineSer import *

from openpyxl.descriptors import (
    Typed,
    Bool,
    NoneSet,
    String,
    Integer,
    Set,
    Float,)


class Shape(Serialisable):

    val = Set(values=(['cone', 'coneToMax', 'box', 'cylinder', 'pyramid', 'pyramidToMax']))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class BarSer(Serialisable):

    invertIfNegative = Bool(nested=True, allow_none=True)
    pictureOptions = Typed(expected_type=PictureOptions, allow_none=True)
    dPt = Typed(expected_type=DPt, allow_none=True)
    dLbls = Typed(expected_type=DLbls, allow_none=True)
    trendline = Typed(expected_type=Trendline, allow_none=True)
    errBars = Typed(expected_type=ErrBars, allow_none=True)
    cat = Typed(expected_type=AxDataSource, allow_none=True)
    val = Typed(expected_type=NumDataSource, allow_none=True)
    shape = Typed(expected_type=Shape, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    def __init__(self,
                 invertIfNegative=None,
                 pictureOptions=None,
                 dPt=None,
                 dLbls=None,
                 trendline=None,
                 errBars=None,
                 cat=None,
                 val=None,
                 shape=None,
                 extLst=None,
                ):
        self.invertIfNegative = invertIfNegative
        self.pictureOptions = pictureOptions
        self.dPt = dPt
        self.dLbls = dLbls
        self.trendline = trendline
        self.errBars = errBars
        self.cat = cat
        self.val = val
        self.shape = shape
        self.extLst = extLst

