
#Autogenerated schema
from openpyxl.descriptors.serialisable import Serialisable
from openpyxl.descriptors import (
    Typed,
    Set,
    MinMax,
)


class SizeRepresents(Serialisable):

    val = Set(values=(['area', 'w']))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class BubbleScale(Serialisable):

    val = MinMax(min=0, max=300)

    def __init__(self,
                 val=100,
                ):
        self.val = val


class BubbleChart(Serialisable):

    varyColors = Bool(nested=True, allow_none=True)
    ser = Typed(expected_type=BubbleSer, allow_none=True)
    dLbls = Typed(expected_type=DLbls, allow_none=True)
    bubble3D = Bool(nested=True, allow_none=True)
    bubbleScale = Typed(expected_type=BubbleScale, allow_none=True)
    showNegBubbles = Bool(nested=True, allow_none=True)
    sizeRepresents = Typed(expected_type=SizeRepresents, allow_none=True)
    axId = Typed(expected_type=UnsignedInt, )
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    __elements__ = ('varyColors', 'ser', 'dLbls', 'bubble3D', 'bubbleScale', 'showNegBubbles', 'sizeRepresents', 'axId', 'extLst')

    def __init__(self,
                 varyColors=None,
                 ser=None,
                 dLbls=None,
                 bubble3D=None,
                 bubbleScale=None,
                 showNegBubbles=None,
                 sizeRepresents=None,
                 axId=None,
                 extLst=None,
                ):
        self.varyColors = varyColors
        self.ser = ser
        self.dLbls = dLbls
        self.bubble3D = bubble3D
        self.bubbleScale = bubbleScale
        self.showNegBubbles = showNegBubbles
        self.sizeRepresents = sizeRepresents
        self.axId = axId
        self.extLst = extLst

