
#Autogenerated schema
from openpyxl.descriptors.serialisable import Serialisable
from openpyxl.descriptors import (
    Typed,
    MinMax,
    )

class HoleSize(Serialisable):

    # needs to serialise to %
    val = MinMax(min=0, max=100)

    def __init__(self,
                 val=10,
                ):
        self.val = val


class FirstSliceAng(Serialisable):

    val = MinMax(min=0, max=360)

    def __init__(self, val=0, ):
        self.val = val


class DoughnutChart(Serialisable):

    firstSliceAng = Typed(expected_type=FirstSliceAng, allow_none=True)
    holeSize = Typed(expected_type=HoleSize, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    __elements__ = ('firstSliceAng', 'holeSize', 'extLst')

    def __init__(self,
                 firstSliceAng=None,
                 holeSize=None,
                 extLst=None,
                ):
        self.firstSliceAng = firstSliceAng
        self.holeSize = holeSize
        self.extLst = extLst

