
#Autogenerated schema
from openpyxl.descriptors.serialisable import Serialisable
from openpyxl.descriptors import (
    Set,
    Float,
    Typed,)

from .LineSer import ExtensionList


class LayoutMode(Serialisable):

    val = Set(values=(['edge', 'factor']))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class LayoutTarget(Serialisable):

    val = Set(values=(['inner', 'outer']))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class ManualLayout(Serialisable):

    layoutTarget = Typed(expected_type=LayoutTarget, allow_none=True)
    xMode = Typed(expected_type=LayoutMode, allow_none=True)
    yMode = Typed(expected_type=LayoutMode, allow_none=True)
    wMode = Typed(expected_type=LayoutMode, allow_none=True)
    hMode = Typed(expected_type=LayoutMode, allow_none=True)
    x = Float(nested=True, allow_none=True)
    y = Float(nested=True, allow_none=True)
    w = Float(nested=True, allow_none=True)
    h = Float(nested=True, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    __elements__ = ('layoutTarget', 'xMode', 'yMode', 'wMode', 'hMode', 'x', 'y', 'w', 'h', 'extLst')

    def __init__(self,
                 layoutTarget=None,
                 xMode=None,
                 yMode=None,
                 wMode=None,
                 hMode=None,
                 x=None,
                 y=None,
                 w=None,
                 h=None,
                 extLst=None,
                ):
        self.layoutTarget = layoutTarget
        self.xMode = xMode
        self.yMode = yMode
        self.wMode = wMode
        self.hMode = hMode
        self.x = x
        self.y = y
        self.w = w
        self.h = h
        self.extLst = extLst


class Layout(Serialisable):

    manualLayout = Typed(expected_type=ManualLayout, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    __elements__ = ('manualLayout', 'extLst')

    def __init__(self,
                 manualLayout=None,
                 extLst=None,
                ):
        self.manualLayout = manualLayout
        self.extLst = extLst
