
#Autogenerated schema
from openpyxl.descriptors.serialisable import Serialisable
from openpyxl.descriptors import (
    Typed,
    Set,)


class ChartLines(Serialisable):

    spPr = Typed(expected_type=ShapeProperties, allow_none=True)

    __elements__ = ('spPr',)

    def __init__(self,
                 spPr=None,
                ):
        self.spPr = spPr


class Grouping(Serialisable):

    val = Set(values=(['percentStacked', 'standard', 'stacked']))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class LineChartShared(Serialisable):

    grouping = Typed(expected_type=Grouping, )
    varyColors = Bool(nested=True, allow_none=True)
    ser = Typed(expected_type=LineSer, allow_none=True)
    dLbls = Typed(expected_type=DLbls, allow_none=True)
    dropLines = Typed(expected_type=ChartLines, allow_none=True)

    __elements__ = ('grouping', 'varyColors', 'ser', 'dLbls', 'dropLines')

    def __init__(self,
                 grouping=None,
                 varyColors=None,
                 ser=None,
                 dLbls=None,
                 dropLines=None,
                ):
        self.grouping = grouping
        self.varyColors = varyColors
        self.ser = ser
        self.dLbls = dLbls
        self.dropLines = dropLines

