#Autogenerated schema

from openpyxl.descriptors import (
    Strict,
    Typed,
    Float,
    MinMax,
    Bool,
    Set,
    String,
    Integer,)

from openpyxl.descriptors.excel import(
    Coordinate,
    Percentage,
    HexBinary,
    TextPoint,
)

class Boolean(Strict):

    val = Bool(allow_none=True)

    def __init__(self,
                 val=None,
                ):
        self.val = val


class Double(Strict):

    val = Float()

    def __init__(self,
                 val=None,
                ):
        self.val = val


class Extension(Strict):

    uri = Typed(expected_type=String, )

    def __init__(self,
                 uri=None,
                ):
        self.uri = uri


class ExtensionList(Strict):

    ext = Typed(expected_type=Extension, allow_none=True)

    def __init__(self,
                 ext=None,
                ):
        self.ext = ext


class AxDataSource(Strict):

    pass

class NumDataSource(Strict):

    pass

class ErrValType(Strict):

    val = Typed(expected_type=Set(values=(['cust', 'fixedVal', 'percentage', 'stdDev', 'stdErr'])))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class ErrBarType(Strict):

    val = Typed(expected_type=Set(values=(['both', 'minus', 'plus'])))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class ErrDir(Strict):

    val = Typed(expected_type=Set(values=(['x', 'y'])))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class Point2D(Strict):

    x = Typed(expected_type=Coordinate, )
    y = Typed(expected_type=Coordinate, )

    def __init__(self,
                 x=None,
                 y=None,
                ):
        self.x = x
        self.y = y


class PositiveSize2D(Strict):

    cx = Typed(expected_type=Integer())
    cy = Typed(expected_type=Integer())

    def __init__(self,
                 cx=None,
                 cy=None,
                ):
        self.cx = cx
        self.cy = cy


class Transform2D(Strict):

    rot = Typed(expected_type=Integer())
    flipH = Typed(expected_type=Bool, allow_none=True)
    flipV = Typed(expected_type=Bool, allow_none=True)
    off = Typed(expected_type=Point2D, allow_none=True)
    ext = Typed(expected_type=PositiveSize2D, allow_none=True)

    def __init__(self,
                 rot=None,
                 flipH=None,
                 flipV=None,
                 off=None,
                 ext=None,
                ):
        self.rot = rot
        self.flipH = flipH
        self.flipV = flipV
        self.off = off
        self.ext = ext


class OfficeArtExtensionList(Strict):

    pass

class LineEndProperties(Strict):

    type = Typed(expected_type=Set(values=(['none', 'triangle', 'stealth', 'diamond', 'oval', 'arrow'])))
    w = Typed(expected_type=Set(values=(['sm', 'med', 'lg'])))
    len = Typed(expected_type=Set(values=(['sm', 'med', 'lg'])))

    def __init__(self,
                 type=None,
                 w=None,
                 len=None,
                ):
        self.type = type
        self.w = w
        self.len = len


class LineProperties(Strict):

    w = Typed(expected_type=Coordinate())
    cap = Typed(expected_type=Set(values=(['rnd', 'sq', 'flat'])))
    cmpd = Typed(expected_type=Set(values=(['sng', 'dbl', 'thickThin', 'thinThick', 'tri'])))
    algn = Typed(expected_type=Set(values=(['ctr', 'in'])))
    headEnd = Typed(expected_type=LineEndProperties, allow_none=True)
    tailEnd = Typed(expected_type=LineEndProperties, allow_none=True)
    extLst = Typed(expected_type=OfficeArtExtensionList, allow_none=True)

    def __init__(self,
                 w=None,
                 cap=None,
                 cmpd=None,
                 algn=None,
                 headEnd=None,
                 tailEnd=None,
                 extLst=None,
                ):
        self.w = w
        self.cap = cap
        self.cmpd = cmpd
        self.algn = algn
        self.headEnd = headEnd
        self.tailEnd = tailEnd
        self.extLst = extLst


class SphereCoords(Strict):

    lat = Typed(expected_type=Integer)
    lon = Typed(expected_type=Integer)
    rev = Typed(expected_type=Integer)

    def __init__(self,
                 lat=None,
                 lon=None,
                 rev=None,
                ):
        self.lat = lat
        self.lon = lon
        self.rev = rev


class Camera(Strict):

    prst = Typed(expected_type=Set(values=(['legacyObliqueTopLeft', 'legacyObliqueTop', 'legacyObliqueTopRight', 'legacyObliqueLeft', 'legacyObliqueFront', 'legacyObliqueRight', 'legacyObliqueBottomLeft', 'legacyObliqueBottom', 'legacyObliqueBottomRight', 'legacyPerspectiveTopLeft', 'legacyPerspectiveTop', 'legacyPerspectiveTopRight', 'legacyPerspectiveLeft', 'legacyPerspectiveFront', 'legacyPerspectiveRight', 'legacyPerspectiveBottomLeft', 'legacyPerspectiveBottom', 'legacyPerspectiveBottomRight', 'orthographicFront', 'isometricTopUp', 'isometricTopDown', 'isometricBottomUp', 'isometricBottomDown', 'isometricLeftUp', 'isometricLeftDown', 'isometricRightUp', 'isometricRightDown', 'isometricOffAxis1Left', 'isometricOffAxis1Right', 'isometricOffAxis1Top', 'isometricOffAxis2Left', 'isometricOffAxis2Right', 'isometricOffAxis2Top', 'isometricOffAxis3Left', 'isometricOffAxis3Right', 'isometricOffAxis3Bottom', 'isometricOffAxis4Left', 'isometricOffAxis4Right', 'isometricOffAxis4Bottom', 'obliqueTopLeft', 'obliqueTop', 'obliqueTopRight', 'obliqueLeft', 'obliqueRight', 'obliqueBottomLeft', 'obliqueBottom', 'obliqueBottomRight', 'perspectiveFront', 'perspectiveLeft', 'perspectiveRight', 'perspectiveAbove', 'perspectiveBelow', 'perspectiveAboveLeftFacing', 'perspectiveAboveRightFacing', 'perspectiveContrastingLeftFacing', 'perspectiveContrastingRightFacing', 'perspectiveHeroicLeftFacing', 'perspectiveHeroicRightFacing', 'perspectiveHeroicExtremeLeftFacing', 'perspectiveHeroicExtremeRightFacing', 'perspectiveRelaxed', 'perspectiveRelaxedModerately'])))
    fov = Typed(expected_type=Integer)
    zoom = Typed(expected_type=Percentage, allow_none=True)
    rot = Typed(expected_type=SphereCoords, allow_none=True)

    def __init__(self,
                 prst=None,
                 fov=None,
                 zoom=None,
                 rot=None,
                ):
        self.prst = prst
        self.fov = fov
        self.zoom = zoom
        self.rot = rot


class LightRig(Strict):

    rig = Typed(expected_type=Set(values=(['legacyFlat1', 'legacyFlat2', 'legacyFlat3', 'legacyFlat4', 'legacyNormal1', 'legacyNormal2', 'legacyNormal3', 'legacyNormal4', 'legacyHarsh1', 'legacyHarsh2', 'legacyHarsh3', 'legacyHarsh4', 'threePt', 'balanced', 'soft', 'harsh', 'flood', 'contrasting', 'morning', 'sunrise', 'sunset', 'chilly', 'freezing', 'flat', 'twoPt', 'glow', 'brightRoom'])))
    dir = Typed(expected_type=Set(values=(['tl', 't', 'tr', 'l', 'r', 'bl', 'b', 'br'])))
    rot = Typed(expected_type=SphereCoords, allow_none=True)

    def __init__(self,
                 rig=None,
                 dir=None,
                 rot=None,
                ):
        self.rig = rig
        self.dir = dir
        self.rot = rot


class Vector3D(Strict):

    dx = Typed(expected_type=Coordinate, )
    dy = Typed(expected_type=Coordinate, )
    dz = Typed(expected_type=Coordinate, )

    def __init__(self,
                 dx=None,
                 dy=None,
                 dz=None,
                ):
        self.dx = dx
        self.dy = dy
        self.dz = dz


class Point3D(Strict):

    x = Typed(expected_type=Coordinate, )
    y = Typed(expected_type=Coordinate, )
    z = Typed(expected_type=Coordinate, )

    def __init__(self,
                 x=None,
                 y=None,
                 z=None,
                ):
        self.x = x
        self.y = y
        self.z = z


class Backdrop(Strict):

    anchor = Typed(expected_type=Point3D, )
    norm = Typed(expected_type=Vector3D, )
    up = Typed(expected_type=Vector3D, )
    extLst = Typed(expected_type=OfficeArtExtensionList, allow_none=True)

    def __init__(self,
                 anchor=None,
                 norm=None,
                 up=None,
                 extLst=None,
                ):
        self.anchor = anchor
        self.norm = norm
        self.up = up
        self.extLst = extLst


class Scene3D(Strict):

    camera = Typed(expected_type=Camera, )
    lightRig = Typed(expected_type=LightRig, )
    backdrop = Typed(expected_type=Backdrop, allow_none=True)
    extLst = Typed(expected_type=OfficeArtExtensionList, allow_none=True)

    def __init__(self,
                 camera=None,
                 lightRig=None,
                 backdrop=None,
                 extLst=None,
                ):
        self.camera = camera
        self.lightRig = lightRig
        self.backdrop = backdrop
        self.extLst = extLst


class Bevel(Strict):

    w = Typed(expected_type=Integer())
    h = Typed(expected_type=Integer())
    prst = Typed(expected_type=Set(values=(['relaxedInset', 'circle', 'slope', 'cross', 'angle', 'softRound', 'convex', 'coolSlant', 'divot', 'riblet', 'hardEdge', 'artDeco'])))

    def __init__(self,
                 w=None,
                 h=None,
                 prst=None,
                ):
        self.w = w
        self.h = h
        self.prst = prst


class Color(Strict):
    # EG_ColorChoice
    pass


class Shape3D(Strict):

    z = Typed(expected_type=Coordinate, allow_none=True)
    extrusionH = Typed(expected_type=Integer())
    contourW = Typed(expected_type=Integer())
    prstMaterial = Typed(expected_type=Set(values=(['legacyMatte', 'legacyPlastic', 'legacyMetal', 'legacyWireframe', 'matte', 'plastic', 'metal', 'warmMatte', 'translucentPowder', 'powder', 'dkEdge', 'softEdge', 'clear', 'flat', 'softmetal'])))
    bevelT = Typed(expected_type=Bevel, allow_none=True)
    bevelB = Typed(expected_type=Bevel, allow_none=True)
    extrusionClr = Typed(expected_type=Color, allow_none=True)
    contourClr = Typed(expected_type=Color, allow_none=True)
    extLst = Typed(expected_type=OfficeArtExtensionList, allow_none=True)

    def __init__(self,
                 z=None,
                 extrusionH=None,
                 contourW=None,
                 prstMaterial=None,
                 bevelT=None,
                 bevelB=None,
                 extrusionClr=None,
                 contourClr=None,
                 extLst=None,
                ):
        self.z = z
        self.extrusionH = extrusionH
        self.contourW = contourW
        self.prstMaterial = prstMaterial
        self.bevelT = bevelT
        self.bevelB = bevelB
        self.extrusionClr = extrusionClr
        self.contourClr = contourClr
        self.extLst = extLst


class ShapeProperties(Strict):

    bwMode = Typed(expected_type=Set(values=(['clr', 'auto', 'gray', 'ltGray', 'invGray', 'grayWhite', 'blackGray', 'blackWhite', 'black', 'white', 'hidden'])))
    xfrm = Typed(expected_type=Transform2D, allow_none=True)
    ln = Typed(expected_type=LineProperties, allow_none=True)
    scene3d = Typed(expected_type=Scene3D, allow_none=True)
    sp3d = Typed(expected_type=Shape3D, allow_none=True)
    extLst = Typed(expected_type=OfficeArtExtensionList, allow_none=True)

    def __init__(self,
                 bwMode=None,
                 xfrm=None,
                 ln=None,
                 scene3d=None,
                 sp3d=None,
                 extLst=None,
                ):
        self.bwMode = bwMode
        self.xfrm = xfrm
        self.ln = ln
        self.scene3d = scene3d
        self.sp3d = sp3d
        self.extLst = extLst


class ErrBars(Strict):

    errDir = Typed(expected_type=ErrDir, allow_none=True)
    errBarType = Typed(expected_type=ErrBarType, )
    errValType = Typed(expected_type=ErrValType, )
    noEndCap = Typed(expected_type=Boolean, allow_none=True)
    plus = Typed(expected_type=NumDataSource, allow_none=True)
    minus = Typed(expected_type=NumDataSource, allow_none=True)
    val = Typed(expected_type=Double, allow_none=True)
    spPr = Typed(expected_type=ShapeProperties, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    def __init__(self,
                 errDir=None,
                 errBarType=None,
                 errValType=None,
                 noEndCap=None,
                 plus=None,
                 minus=None,
                 val=None,
                 spPr=None,
                 extLst=None,
                ):
        self.errDir = errDir
        self.errBarType = errBarType
        self.errValType = errValType
        self.noEndCap = noEndCap
        self.plus = plus
        self.minus = minus
        self.val = val
        self.spPr = spPr
        self.extLst = extLst


class EmbeddedWAVAudioFile(Strict):

    name = Typed(expected_type=String, allow_none=True)

    def __init__(self,
                 name=None,
                ):
        self.name = name


class Hyperlink(Strict):

    invalidUrl = Typed(expected_type=String, allow_none=True)
    action = Typed(expected_type=String, allow_none=True)
    tgtFrame = Typed(expected_type=String, allow_none=True)
    tooltip = Typed(expected_type=String, allow_none=True)
    history = Typed(expected_type=Bool, allow_none=True)
    highlightClick = Typed(expected_type=Bool, allow_none=True)
    endSnd = Typed(expected_type=Bool, allow_none=True)
    snd = Typed(expected_type=EmbeddedWAVAudioFile, allow_none=True)
    extLst = Typed(expected_type=OfficeArtExtensionList, allow_none=True)

    def __init__(self,
                 invalidUrl=None,
                 action=None,
                 tgtFrame=None,
                 tooltip=None,
                 history=None,
                 highlightClick=None,
                 endSnd=None,
                 snd=None,
                 extLst=None,
                ):
        self.invalidUrl = invalidUrl
        self.action = action
        self.tgtFrame = tgtFrame
        self.tooltip = tooltip
        self.history = history
        self.highlightClick = highlightClick
        self.endSnd = endSnd
        self.snd = snd
        self.extLst = extLst


class TextFont(Strict):

    typeface = Typed(expected_type=String())
    panose = Typed(expected_type=HexBinary, allow_none=True)
    pitchFamily = Typed(expected_type=MinMax, allow_none=True)
    charset = Typed(expected_type=MinMax, allow_none=True)

    def __init__(self,
                 typeface=None,
                 panose=None,
                 pitchFamily=None,
                 charset=None,
                ):
        self.typeface = typeface
        self.panose = panose
        self.pitchFamily = pitchFamily
        self.charset = charset


class TextCharacterProperties(Strict):

    kumimoji = Typed(expected_type=Bool, allow_none=True)
    lang = Typed(expected_type=String, allow_none=True)
    altLang = Typed(expected_type=String, allow_none=True)
    sz = Typed(expected_type=Integer())
    b = Typed(expected_type=Bool, allow_none=True)
    i = Typed(expected_type=Bool, allow_none=True)
    u = Typed(expected_type=Set(values=(['none', 'words', 'sng', 'dbl', 'heavy', 'dotted', 'dottedHeavy', 'dash', 'dashHeavy', 'dashLong', 'dashLongHeavy', 'dotDash', 'dotDashHeavy', 'dotDotDash', 'dotDotDashHeavy', 'wavy', 'wavyHeavy', 'wavyDbl'])))
    strike = Typed(expected_type=Set(values=(['noStrike', 'sngStrike', 'dblStrike'])))
    kern = Typed(expected_type=Integer())
    cap = Typed(expected_type=Set(values=(['none', 'small', 'all'])))
    spc = Typed(expected_type=TextPoint, allow_none=True)
    normalizeH = Typed(expected_type=Bool, allow_none=True)
    baseline = Typed(expected_type=String, allow_none=True)
    noProof = Typed(expected_type=Bool, allow_none=True)
    dirty = Typed(expected_type=Bool, allow_none=True)
    err = Typed(expected_type=Bool, allow_none=True)
    smtClean = Typed(expected_type=Bool, allow_none=True)
    smtId = Typed(expected_type=Integer, allow_none=True)
    bmk = Typed(expected_type=String, allow_none=True)
    ln = Typed(expected_type=LineProperties, allow_none=True)
    highlight = Typed(expected_type=Color, allow_none=True)
    latin = Typed(expected_type=TextFont, allow_none=True)
    ea = Typed(expected_type=TextFont, allow_none=True)
    cs = Typed(expected_type=TextFont, allow_none=True)
    sym = Typed(expected_type=TextFont, allow_none=True)
    hlinkClick = Typed(expected_type=Hyperlink, allow_none=True)
    hlinkMouseOver = Typed(expected_type=Hyperlink, allow_none=True)
    rtl = Typed(expected_type=Boolean, allow_none=True)
    extLst = Typed(expected_type=OfficeArtExtensionList, allow_none=True)

    def __init__(self,
                 kumimoji=None,
                 lang=None,
                 altLang=None,
                 sz=None,
                 b=None,
                 i=None,
                 u=None,
                 strike=None,
                 kern=None,
                 cap=None,
                 spc=None,
                 normalizeH=None,
                 baseline=None,
                 noProof=None,
                 dirty=None,
                 err=None,
                 smtClean=None,
                 smtId=None,
                 bmk=None,
                 ln=None,
                 highlight=None,
                 latin=None,
                 ea=None,
                 cs=None,
                 sym=None,
                 hlinkClick=None,
                 hlinkMouseOver=None,
                 rtl=None,
                 extLst=None,
                ):
        self.kumimoji = kumimoji
        self.lang = lang
        self.altLang = altLang
        self.sz = sz
        self.b = b
        self.i = i
        self.u = u
        self.strike = strike
        self.kern = kern
        self.cap = cap
        self.spc = spc
        self.normalizeH = normalizeH
        self.baseline = baseline
        self.noProof = noProof
        self.dirty = dirty
        self.err = err
        self.smtClean = smtClean
        self.smtId = smtId
        self.bmk = bmk
        self.ln = ln
        self.highlight = highlight
        self.latin = latin
        self.ea = ea
        self.cs = cs
        self.sym = sym
        self.hlinkClick = hlinkClick
        self.hlinkMouseOver = hlinkMouseOver
        self.rtl = rtl
        self.extLst = extLst


class TextTabStop(Strict):

    pos = Typed(expected_type=Coordinate, allow_none=True)
    algn = Typed(expected_type=Set(values=(['l', 'ctr', 'r', 'dec'])))

    def __init__(self,
                 pos=None,
                 algn=None,
                ):
        self.pos = pos
        self.algn = algn


class TextTabStopList(Strict):

    tab = Typed(expected_type=TextTabStop, allow_none=True)

    def __init__(self,
                 tab=None,
                ):
        self.tab = tab


class TextSpacing(Strict):

    pass

class TextParagraphProperties(Strict):

    marL = Typed(expected_type=Coordinate)
    marR = Typed(expected_type=Coordinate)
    lvl = Typed(expected_type=Integer())
    indent = Typed(expected_type=Coordinate)
    algn = Typed(expected_type=Set(values=(['l', 'ctr', 'r', 'just', 'justLow', 'dist', 'thaiDist'])))
    defTabSz = Typed(expected_type=Coordinate, allow_none=True)
    rtl = Typed(expected_type=Bool, allow_none=True)
    eaLnBrk = Typed(expected_type=Bool, allow_none=True)
    fontAlgn = Typed(expected_type=Set(values=(['auto', 't', 'ctr', 'base', 'b'])))
    latinLnBrk = Typed(expected_type=Bool, allow_none=True)
    hangingPunct = Typed(expected_type=Bool, allow_none=True)
    lnSpc = Typed(expected_type=TextSpacing, allow_none=True)
    spcBef = Typed(expected_type=TextSpacing, allow_none=True)
    spcAft = Typed(expected_type=TextSpacing, allow_none=True)
    tabLst = Typed(expected_type=TextTabStopList, allow_none=True)
    defRPr = Typed(expected_type=TextCharacterProperties, allow_none=True)
    extLst = Typed(expected_type=OfficeArtExtensionList, allow_none=True)

    def __init__(self,
                 marL=None,
                 marR=None,
                 lvl=None,
                 indent=None,
                 algn=None,
                 defTabSz=None,
                 rtl=None,
                 eaLnBrk=None,
                 fontAlgn=None,
                 latinLnBrk=None,
                 hangingPunct=None,
                 lnSpc=None,
                 spcBef=None,
                 spcAft=None,
                 tabLst=None,
                 defRPr=None,
                 extLst=None,
                ):
        self.marL = marL
        self.marR = marR
        self.lvl = lvl
        self.indent = indent
        self.algn = algn
        self.defTabSz = defTabSz
        self.rtl = rtl
        self.eaLnBrk = eaLnBrk
        self.fontAlgn = fontAlgn
        self.latinLnBrk = latinLnBrk
        self.hangingPunct = hangingPunct
        self.lnSpc = lnSpc
        self.spcBef = spcBef
        self.spcAft = spcAft
        self.tabLst = tabLst
        self.defRPr = defRPr
        self.extLst = extLst


class TextListStyle(Strict):

    defPPr = Typed(expected_type=TextParagraphProperties, allow_none=True)
    lvl1pPr = Typed(expected_type=TextParagraphProperties, allow_none=True)
    lvl2pPr = Typed(expected_type=TextParagraphProperties, allow_none=True)
    lvl3pPr = Typed(expected_type=TextParagraphProperties, allow_none=True)
    lvl4pPr = Typed(expected_type=TextParagraphProperties, allow_none=True)
    lvl5pPr = Typed(expected_type=TextParagraphProperties, allow_none=True)
    lvl6pPr = Typed(expected_type=TextParagraphProperties, allow_none=True)
    lvl7pPr = Typed(expected_type=TextParagraphProperties, allow_none=True)
    lvl8pPr = Typed(expected_type=TextParagraphProperties, allow_none=True)
    lvl9pPr = Typed(expected_type=TextParagraphProperties, allow_none=True)
    extLst = Typed(expected_type=OfficeArtExtensionList, allow_none=True)

    def __init__(self,
                 defPPr=None,
                 lvl1pPr=None,
                 lvl2pPr=None,
                 lvl3pPr=None,
                 lvl4pPr=None,
                 lvl5pPr=None,
                 lvl6pPr=None,
                 lvl7pPr=None,
                 lvl8pPr=None,
                 lvl9pPr=None,
                 extLst=None,
                ):
        self.defPPr = defPPr
        self.lvl1pPr = lvl1pPr
        self.lvl2pPr = lvl2pPr
        self.lvl3pPr = lvl3pPr
        self.lvl4pPr = lvl4pPr
        self.lvl5pPr = lvl5pPr
        self.lvl6pPr = lvl6pPr
        self.lvl7pPr = lvl7pPr
        self.lvl8pPr = lvl8pPr
        self.lvl9pPr = lvl9pPr
        self.extLst = extLst


class TextParagraph(Strict):

    pPr = Typed(expected_type=TextParagraphProperties, allow_none=True)
    endParaRPr = Typed(expected_type=TextCharacterProperties, allow_none=True)

    def __init__(self,
                 pPr=None,
                 endParaRPr=None,
                ):
        self.pPr = pPr
        self.endParaRPr = endParaRPr


class GeomGuide(Strict):

    name = Typed(expected_type=String())
    fmla = Typed(expected_type=String())

    def __init__(self,
                 name=None,
                 fmla=None,
                ):
        self.name = name
        self.fmla = fmla


class GeomGuideList(Strict):

    gd = Typed(expected_type=GeomGuide, allow_none=True)

    def __init__(self,
                 gd=None,
                ):
        self.gd = gd


class PresetTextShape(Strict):

    prst = Typed(expected_type=Set(values=(['textNoShape', 'textPlain',
                                            'textStop', 'textTriangle', 'textTriangleInverted', 'textChevron',
                                            'textChevronInverted', 'textRingInside', 'textRingOutside', 'textArchUp',
                                            'textArchDown', 'textCircle', 'textButton', 'textArchUpPour',
                                            'textArchDownPour', 'textCirclePour', 'textButtonPour', 'textCurveUp',
                                            'textCurveDown', 'textCanUp', 'textCanDown', 'textWave1', 'textWave2',
                                            'textDoubleWave1', 'textWave4', 'textInflate', 'textDeflate',
                                            'textInflateBottom', 'textDeflateBottom', 'textInflateTop',
                                            'textDeflateTop', 'textDeflateInflate', 'textDeflateInflateDeflate',
                                            'textFadeRight', 'textFadeLeft', 'textFadeUp', 'textFadeDown',
                                            'textSlantUp', 'textSlantDown', 'textCascadeUp', 'textCascadeDown'])))
    avLst = Typed(expected_type=GeomGuideList, allow_none=True)

    def __init__(self,
                 prst=None,
                 avLst=None,
                ):
        self.prst = prst
        self.avLst = avLst


class TextBodyProperties(Strict):

    rot = Typed(expected_type=Integer())
    spcFirstLastPara = Typed(expected_type=Bool, allow_none=True)
    vertOverflow = Typed(expected_type=Set(values=(['overflow', 'ellipsis', 'clip'])))
    horzOverflow = Typed(expected_type=Set(values=(['overflow', 'clip'])))
    vert = Typed(expected_type=Set(values=(['horz', 'vert', 'vert270',
                                            'wordArtVert', 'eaVert', 'mongolianVert', 'wordArtVertRtl'])))
    wrap = Typed(expected_type=Set(values=(['none', 'square'])))
    lIns = Typed(expected_type=Coordinate, allow_none=True)
    tIns = Typed(expected_type=Coordinate, allow_none=True)
    rIns = Typed(expected_type=Coordinate, allow_none=True)
    bIns = Typed(expected_type=Coordinate, allow_none=True)
    numCol = Typed(expected_type=Integer())
    spcCol = Typed(expected_type=Coordinate)
    rtlCol = Typed(expected_type=Bool, allow_none=True)
    fromWordArt = Typed(expected_type=Bool, allow_none=True)
    anchor = Typed(expected_type=Set(values=(['t', 'ctr', 'b', 'just', 'dist'])))
    anchorCtr = Typed(expected_type=Bool, allow_none=True)
    forceAA = Typed(expected_type=Bool, allow_none=True)
    upright = Typed(expected_type=Bool, allow_none=True)
    compatLnSpc = Typed(expected_type=Bool, allow_none=True)
    prstTxWarp = Typed(expected_type=PresetTextShape, allow_none=True)
    scene3d = Typed(expected_type=Scene3D, allow_none=True)
    extLst = Typed(expected_type=OfficeArtExtensionList, allow_none=True)

    def __init__(self,
                 rot=None,
                 spcFirstLastPara=None,
                 vertOverflow=None,
                 horzOverflow=None,
                 vert=None,
                 wrap=None,
                 lIns=None,
                 tIns=None,
                 rIns=None,
                 bIns=None,
                 numCol=None,
                 spcCol=None,
                 rtlCol=None,
                 fromWordArt=None,
                 anchor=None,
                 anchorCtr=None,
                 forceAA=None,
                 upright=None,
                 compatLnSpc=None,
                 prstTxWarp=None,
                 scene3d=None,
                 extLst=None,
                ):
        self.rot = rot
        self.spcFirstLastPara = spcFirstLastPara
        self.vertOverflow = vertOverflow
        self.horzOverflow = horzOverflow
        self.vert = vert
        self.wrap = wrap
        self.lIns = lIns
        self.tIns = tIns
        self.rIns = rIns
        self.bIns = bIns
        self.numCol = numCol
        self.spcCol = spcCol
        self.rtlCol = rtlCol
        self.fromWordArt = fromWordArt
        self.anchor = anchor
        self.anchorCtr = anchorCtr
        self.forceAA = forceAA
        self.upright = upright
        self.compatLnSpc = compatLnSpc
        self.prstTxWarp = prstTxWarp
        self.scene3d = scene3d
        self.extLst = extLst


class TextBody(Strict):

    bodyPr = Typed(expected_type=TextBodyProperties, )
    lstStyle = Typed(expected_type=TextListStyle, allow_none=True)
    p = Typed(expected_type=TextParagraph, )

    def __init__(self,
                 bodyPr=None,
                 lstStyle=None,
                 p=None,
                ):
        self.bodyPr = bodyPr
        self.lstStyle = lstStyle
        self.p = p


class NumFmt(Strict):

    formatCode = String(allow_none=True)
    sourceLinked = Bool(allow_none=True)

    def __init__(self,
                 formatCode=None,
                 sourceLinked=None,
                ):
        self.formatCode = formatCode
        self.sourceLinked = sourceLinked


class Tx(Strict):

    pass

class LayoutMode(Strict):

    val = Set(values=(['edge', 'factor']))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class LayoutTarget(Strict):

    val = Set(values=(['inner', 'outer']))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class ManualLayout(Strict):

    layoutTarget = Typed(expected_type=LayoutTarget, allow_none=True)
    xMode = Typed(expected_type=LayoutMode, allow_none=True)
    yMode = Typed(expected_type=LayoutMode, allow_none=True)
    wMode = Typed(expected_type=LayoutMode, allow_none=True)
    hMode = Typed(expected_type=LayoutMode, allow_none=True)
    x = Float(allow_none=True)
    y = Float(allow_none=True)
    w = Float(allow_none=True)
    h = Float(allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    def __init__(self,
                 layoutTarget=None,
                 xMode=None,
                 yMode=None,
                 wMode=None,
                 hMode=None,
                 x=None,
                 y=None,
                 w=None,
                 h=None,
                 extLst=None,
                ):
        self.layoutTarget = layoutTarget
        self.xMode = xMode
        self.yMode = yMode
        self.wMode = wMode
        self.hMode = hMode
        self.x = x
        self.y = y
        self.w = w
        self.h = h
        self.extLst = extLst


class Layout(Strict):

    manualLayout = Typed(expected_type=ManualLayout, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    def __init__(self,
                 manualLayout=None,
                 extLst=None,
                ):
        self.manualLayout = manualLayout
        self.extLst = extLst


class TrendlineLbl(Strict):

    layout = Typed(expected_type=Layout, allow_none=True)
    tx = Typed(expected_type=Tx, allow_none=True)
    numFmt = Typed(expected_type=NumFmt, allow_none=True)
    spPr = Typed(expected_type=ShapeProperties, allow_none=True)
    txPr = Typed(expected_type=TextBody, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    def __init__(self,
                 layout=None,
                 tx=None,
                 numFmt=None,
                 spPr=None,
                 txPr=None,
                 extLst=None,
                ):
        self.layout = layout
        self.tx = tx
        self.numFmt = numFmt
        self.spPr = spPr
        self.txPr = txPr
        self.extLst = extLst



class Period(Strict):

    val = Integer()

    def __init__(self,
                 val=None,
                ):
        self.val = val


class Order(Strict):

    val = Integer()

    def __init__(self,
                 val=None,
                ):
        self.val = val


class TrendlineType(Strict):

    val = Set(values=(['exp', 'linear', 'log', 'movingAvg', 'poly', 'power']))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class Trendline(Strict):

    name = String(allow_none=True)
    spPr = Typed(expected_type=ShapeProperties, allow_none=True)
    trendlineType = Typed(expected_type=TrendlineType, )
    order = Typed(expected_type=Order, allow_none=True)
    period = Typed(expected_type=Period, allow_none=True)
    forward = Typed(expected_type=Double, allow_none=True)
    backward = Typed(expected_type=Double, allow_none=True)
    intercept = Typed(expected_type=Double, allow_none=True)
    dispRSqr = Typed(expected_type=Boolean, allow_none=True)
    dispEq = Typed(expected_type=Boolean, allow_none=True)
    trendlineLbl = Typed(expected_type=TrendlineLbl, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    def __init__(self,
                 name=None,
                 spPr=None,
                 trendlineType=None,
                 order=None,
                 period=None,
                 forward=None,
                 backward=None,
                 intercept=None,
                 dispRSqr=None,
                 dispEq=None,
                 trendlineLbl=None,
                 extLst=None,
                ):
        self.name = name
        self.spPr = spPr
        self.trendlineType = trendlineType
        self.order = order
        self.period = period
        self.forward = forward
        self.backward = backward
        self.intercept = intercept
        self.dispRSqr = dispRSqr
        self.dispEq = dispEq
        self.trendlineLbl = trendlineLbl
        self.extLst = extLst


class DLbl(Strict):

    idx = Integer()
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    def __init__(self,
                 idx=None,
                 extLst=None,
                ):
        self.idx = idx
        self.extLst = extLst


class DLbls(Strict):

    dLbl = Typed(expected_type=DLbl, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    def __init__(self,
                 dLbl=None,
                 extLst=None,
                ):
        self.dLbl = dLbl
        self.extLst = extLst


class PictureStackUnit(Strict):

    val = Typed(expected_type=Float())

    def __init__(self,
                 val=None,
                ):
        self.val = val


class PictureFormat(Strict):

    val = Set(values=(['stretch', 'stack', 'stackScale']))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class PictureOptions(Strict):

    applyToFront = Typed(expected_type=Boolean, allow_none=True)
    applyToSides = Typed(expected_type=Boolean, allow_none=True)
    applyToEnd = Typed(expected_type=Boolean, allow_none=True)
    pictureFormat = Typed(expected_type=PictureFormat, allow_none=True)
    pictureStackUnit = Typed(expected_type=PictureStackUnit, allow_none=True)

    def __init__(self,
                 applyToFront=None,
                 applyToSides=None,
                 applyToEnd=None,
                 pictureFormat=None,
                 pictureStackUnit=None,
                ):
        self.applyToFront = applyToFront
        self.applyToSides = applyToSides
        self.applyToEnd = applyToEnd
        self.pictureFormat = pictureFormat
        self.pictureStackUnit = pictureStackUnit


class UnsignedInt(Strict):

    val = Typed(expected_type=Integer, )

    def __init__(self,
                 val=None,
                ):
        self.val = val


class Marker(Strict):

    symbol = Set(values=(['circle', 'dash', 'diamond', 'dot', 'none', 'picture', 'plus', 'square', 'star', 'triangle', 'x', 'auto']))
    size = MinMax(min=2, max=72)
    spPr = Typed(expected_type=ShapeProperties, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    def __init__(self,
                 symbol=None,
                 size=None,
                 spPr=None,
                 extLst=None,
                ):
        self.symbol = symbol
        self.size = size
        self.spPr = spPr
        self.extLst = extLst


class DPt(Strict):

    idx = Typed(expected_type=UnsignedInt, )
    invertIfNegative = Typed(expected_type=Boolean, allow_none=True)
    marker = Typed(expected_type=Marker, allow_none=True)
    bubble3D = Typed(expected_type=Boolean, allow_none=True)
    explosion = Typed(expected_type=UnsignedInt, allow_none=True)
    spPr = Typed(expected_type=ShapeProperties, allow_none=True)
    pictureOptions = Typed(expected_type=PictureOptions, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    def __init__(self,
                 idx=None,
                 invertIfNegative=None,
                 marker=None,
                 bubble3D=None,
                 explosion=None,
                 spPr=None,
                 pictureOptions=None,
                 extLst=None,
                ):
        self.idx = idx
        self.invertIfNegative = invertIfNegative
        self.marker = marker
        self.bubble3D = bubble3D
        self.explosion = explosion
        self.spPr = spPr
        self.pictureOptions = pictureOptions
        self.extLst = extLst


class LineSer(Strict):

    marker = Typed(expected_type=Marker, allow_none=True)
    dPt = Typed(expected_type=DPt, allow_none=True)
    dLbls = Typed(expected_type=DLbls, allow_none=True)
    trendline = Typed(expected_type=Trendline, allow_none=True)
    errBars = Typed(expected_type=ErrBars, allow_none=True)
    cat = Typed(expected_type=AxDataSource, allow_none=True)
    val = Typed(expected_type=NumDataSource, allow_none=True)
    smooth = Typed(expected_type=Boolean, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    def __init__(self,
                 marker=None,
                 dPt=None,
                 dLbls=None,
                 trendline=None,
                 errBars=None,
                 cat=None,
                 val=None,
                 smooth=None,
                 extLst=None,
                ):
        self.marker = marker
        self.dPt = dPt
        self.dLbls = dLbls
        self.trendline = trendline
        self.errBars = errBars
        self.cat = cat
        self.val = val
        self.smooth = smooth
        self.extLst = extLst

