
#Autogenerated schema
from openpyxl.descriptors.serialisable import Serialisable
from openpyxl.descriptors import (
    Typed,
    Bool,
    Integer,
    Set,
    )
from openpyxl.descriptors.excel import ExtensionList

from .shapes import ShapeProperties
from .chartBase import GapAmount, ChartLines, UpDownBars
from .label import DLbls
from .series import LineSer


class Grouping(Serialisable):

    val = Set(values=(['percentStacked', 'standard', 'stacked']))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class _LineChartBase(Serialisable):

    grouping = Typed(expected_type=Grouping, )
    varyColors = Bool(nested=True, allow_none=True)
    ser = Typed(expected_type=LineSer, allow_none=True)
    dLbls = Typed(expected_type=DLbls, allow_none=True)
    dropLines = Typed(expected_type=ChartLines, allow_none=True)

    __elements__ = ('grouping', 'varyColors', 'ser', 'dLbls', 'dropLines')

    def __init__(self,
                 grouping=None,
                 varyColors=None,
                 ser=None,
                 dLbls=None,
                 dropLines=None,
                ):
        self.grouping = grouping
        self.varyColors = varyColors
        self.ser = ser
        self.dLbls = dLbls
        self.dropLines = dropLines


class LineChart(_LineChartBase):


    hiLowLines = Typed(expected_type=ChartLines, allow_none=True)
    upDownBars = Typed(expected_type=UpDownBars, allow_none=True)
    marker = Bool(nested=True, allow_none=True)
    smooth = Bool(nested=True, allow_none=True)
    axId = Integer(nested=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    __elements__ = ('hiLowLines', 'upDownBars', 'marker', 'smooth', 'axId', 'extLst')

    def __init__(self,
                 hiLowLines=None,
                 upDownBars=None,
                 marker=None,
                 smooth=None,
                 axId=None,
                 extLst=None,
                ):
        self.hiLowLines = hiLowLines
        self.upDownBars = upDownBars
        self.marker = marker
        self.smooth = smooth
        self.axId = axId
        self.extLst = extLst


class LineChart(_LineChartBase):


    gapDepth = Typed(expected_type=GapAmount, allow_none=True)
    hiLowLines = Typed(expected_type=ChartLines, allow_none=True)
    upDownBars = Typed(expected_type=UpDownBars, allow_none=True)
    marker = Bool(nested=True, allow_none=True)
    smooth = Bool(nested=True, allow_none=True)
    axId = Integer(nested=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    __elements__ = ('gapDepth', 'hiLowLines', 'upDownBars', 'marker', 'smooth', 'axId', 'extLst')

    def __init__(self,
                 gapDepth=None,
                 hiLowLines=None,
                 upDownBars=None,
                 marker=None,
                 smooth=None,
                 axId=None,
                 extLst=None,
                ):
        self.gapDepth = gapDepth
        self.hiLowLines = hiLowLines
        self.upDownBars = upDownBars
        self.marker = marker
        self.smooth = smooth
        self.axId = axId
        self.extLst = extLst
