
#Autogenerated schema
from openpyxl.descriptors.serialisable import Serialisable
from openpyxl.descriptors import (
    Typed,
    Set,
    MinMax,
)


class ChartLines(Serialisable):

    spPr = Typed(expected_type=ShapeProperties, allow_none=True)

    __elements__ = ('spPr',)

    def __init__(self,
                 spPr=None,
                ):
        self.spPr = spPr


class SecondPieSize(Serialisable):

    # needs to serialise to %
    val = MinMax(min=0, max=200)

    def __init__(self,
                 val=None,
                ):
        self.val = val


class CustSplit(Serialisable):

    secondPiePt = Typed(expected_type=UnsignedInt, allow_none=True)

    __elements__ = ('secondPiePt',)

    def __init__(self,
                 secondPiePt=None,
                ):
        self.secondPiePt = secondPiePt


class SplitType(Serialisable):

    val = Set(values=(['auto', 'cust', 'percent', 'pos', 'val']))

    def __init__(self,
                 val=None,
                ):
        self.val = val



class OfPieType(Serialisable):

    val = Set(values=(['pie', 'bar']))

    def __init__(self,
                 val=None,
                ):
        self.val = val


class OfPieChart(Serialisable):

    ofPieType = Typed(expected_type=OfPieType, )
    gapWidth = Typed(expected_type=GapAmount, allow_none=True)
    splitType = Typed(expected_type=SplitType, allow_none=True)
    splitPos = Float(nested=True, allow_none=True)
    custSplit = Typed(expected_type=CustSplit, allow_none=True)
    secondPieSize = Typed(expected_type=SecondPieSize, allow_none=True)
    serLines = Typed(expected_type=ChartLines, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    __elements__ = ('ofPieType', 'gapWidth', 'splitType', 'splitPos', 'custSplit', 'secondPieSize', 'serLines', 'extLst')

    def __init__(self,
                 ofPieType=None,
                 gapWidth=None,
                 splitType=None,
                 splitPos=None,
                 custSplit=None,
                 secondPieSize=None,
                 serLines=None,
                 extLst=None,
                ):
        self.ofPieType = ofPieType
        self.gapWidth = gapWidth
        self.splitType = splitType
        self.splitPos = splitPos
        self.custSplit = custSplit
        self.secondPieSize = secondPieSize
        self.serLines = serLines
        self.extLst = extLst

