
#Autogenerated schema
from openpyxl.descriptors.serialisable import Serialisable
from openpyxl.descriptors import (
    Typed,)


class PieSer(Serialisable):

    explosion = Typed(expected_type=UnsignedInt, allow_none=True)
    dPt = Typed(expected_type=DPt, allow_none=True)
    dLbls = Typed(expected_type=DLbls, allow_none=True)
    cat = Typed(expected_type=AxDataSource, allow_none=True)
    val = Typed(expected_type=NumDataSource, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    __elements__ = ('explosion', 'dPt', 'dLbls', 'cat', 'val', 'extLst')

    def __init__(self,
                 explosion=None,
                 dPt=None,
                 dLbls=None,
                 cat=None,
                 val=None,
                 extLst=None,
                ):
        self.explosion = explosion
        self.dPt = dPt
        self.dLbls = dLbls
        self.cat = cat
        self.val = val
        self.extLst = extLst


class PieChartShared(Serialisable):

    varyColors = Bool(nested=True, allow_none=True)
    ser = Typed(expected_type=PieSer, allow_none=True)
    dLbls = Typed(expected_type=DLbls, allow_none=True)

    __elements__ = ('varyColors', 'ser', 'dLbls')

    def __init__(self,
                 varyColors=None,
                 ser=None,
                 dLbls=None,
                ):
        self.varyColors = varyColors
        self.ser = ser
        self.dLbls = dLbls

