
#Autogenerated schema
from openpyxl.descriptors.serialisable import Serialisable
from openpyxl.descriptors import (
    Typed,
    MinMax,
)


class FirstSliceAng(Serialisable):

    val = MinMax(min=0, max=360)

    def __init__(self,
                 val=None,
                ):
        self.val = val


class PieChart(Serialisable):

    as_3D = True

    firstSliceAng = Typed(expected_type=FirstSliceAng, allow_none=True) #2d
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    __elements__ = ('firstSliceAng', 'extLst')

    def __init__(self,
                 firstSliceAng=None,
                 extLst=None,
                ):
        self.firstSliceAng = firstSliceAng
        self.extLst = extLst

