
#Autogenerated schema
from openpyxl.descriptors.serialisable import Serialisable
from openpyxl.descriptors import (
    Typed,
    Integer,
    Bool,
)
from openpyxl.descriptors.excel import ExtensionList

from .shapes import ShapeProperties
from .series import SurfaceSer


class BandFmt(Serialisable):

    idx = Integer(nested=True)
    spPr = Typed(expected_type=ShapeProperties, allow_none=True)

    __elements__ = ('idx', 'spPr')

    def __init__(self,
                 idx=None,
                 spPr=None,
                ):
        self.idx = idx
        self.spPr = spPr


class BandFmts(Serialisable):

    bandFmt = Typed(expected_type=BandFmt, allow_none=True)

    __elements__ = ('bandFmt',)

    def __init__(self,
                 bandFmt=None,
                ):
        self.bandFmt = bandFmt


class _SurfaceChartBase(Serialisable):

    wireframe = Bool(nested=True, allow_none=True)
    ser = Typed(expected_type=SurfaceSer, allow_none=True)
    bandFmts = Typed(expected_type=BandFmts, allow_none=True)

    __elements__ = ('wireframe', 'ser', 'bandFmts')

    def __init__(self,
                 wireframe=None,
                 ser=None,
                 bandFmts=None,
                ):
        self.wireframe = wireframe
        self.ser = ser
        self.bandFmts = bandFmts


class SurfaceChart(Serialisable):

    tagname = "surfaceChart"

    axId = Integer(nested=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    __elements__ = ('axId', 'extLst')

    def __init__(self,
                 axId=None,
                 extLst=None,
                ):
        self.axId = axId
        self.extLst = extLst


class SurfaceChart3D(SurfaceChart):

    tagname = "surface3DChart"
