#Autogenerated schema
        from openpyxl.descriptors.serialisable import Serialisable
        from openpyxl.descriptors import (
    Typed,
    String,)


class Extension(Serialisable):

    uri = String()

    def __init__(self,
                 uri=None,
                ):
        self.uri = uri


class ExtensionList(Serialisable):

    ext = Typed(expected_type=Extension, allow_none=True)

    def __init__(self,
                 ext=None,
                ):
        self.ext = ext


class NumDataSource(Serialisable):

    pass

class AxDataSource(Serialisable):

    pass

class SurfaceSer(Serialisable):

    cat = Typed(expected_type=AxDataSource, allow_none=True)
    val = Typed(expected_type=NumDataSource, allow_none=True)
    extLst = Typed(expected_type=ExtensionList, allow_none=True)

    def __init__(self,
                 cat=None,
                 val=None,
                 extLst=None,
                ):
        self.cat = cat
        self.val = val
        self.extLst = extLst

